window.SIAOS_PRODUCTS = [
  {slug:'clear-quartz-bracelet',name:'Clear Quartz Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.8',reviews:86,badge:'Most Rated',sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['A clear, versatile crystal bracelet for everyday spiritual practice.','Chosen for meditation, focus and intention-setting rituals.'],images:['clear-quartz-bracelet-01.png','clear-quartz-bracelet-02.png']},
  {slug:'green-aventurine-bracelet',name:'Green Aventurine Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.7',reviews:61,sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['A soothing green stone bracelet selected for mindful routines.','A meaningful gift for new beginnings and steady intentions.'],images:['green-aventurine-bracelet-01.png','green-aventurine-bracelet-02.png']},
  {slug:'lapis-lazuli-bracelet',name:'Lapis Lazuli Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.8',reviews:73,sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['Deep blue beads chosen for reflection and clear communication.','An elegant companion for journaling and contemplative practice.'],images:['lapis-lazuli-bracelet-01.png','lapis-lazuli-bracelet-02.png']},
  {slug:'mohini-ittar',name:'Mohini Ittar',price:'₹2,500',category:'Ittar',rating:'4.9',reviews:118,badge:'Most Selling',sizes:['6 ml','12 ml'],delivery:'Estimated delivery in 3–6 business days',benefits:['A concentrated traditional fragrance for personal rituals and daily wear.','Warm, long-lasting character in a compact glass bottle.'],images:['mohini-ittar-01.png','mohini-ittar-02.png']},
  {slug:'moon-stone-bracelet',name:'Moon Stone Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.7',reviews:58,sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['Soft luminous beads selected for reflective evening practices.','A graceful piece for intention-led personal rituals.'],images:['moon-stone-bracelet-01.png','moon-stone-bracelet-02.png']},
  {slug:'pyrite-bracelet',name:'Pyrite Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.8',reviews:91,badge:'Most Rated',sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['A metallic-golden stone bracelet selected for confidence rituals.','Designed as a practical, polished everyday accessory.'],images:['pyrite-bracelet-01.png','pyrite-bracelet-02.png']},
  {slug:'raksha-nazar-kavach',name:'Raksha Nazar Kavach',price:'₹22,000',category:'Kavach',rating:'4.9',reviews:42,sizes:['Standard'],delivery:'Estimated delivery in 5–8 business days',benefits:['A carefully presented protective keepsake for a sacred space.','Supplied in a gift-ready presentation box.'],images:['raksha-nazar-kavach-01.png','raksha-nazar-kavach-02.png','raksha-nazar-kavach-03.png']},
  {slug:'red-hakik-bracelet',name:'Red Hakik Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.6',reviews:47,sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['Rich red beads chosen for grounded personal practices.','A strong accent for everyday spiritual wear.'],images:['red-hakik-bracelet-01.png','red-hakik-bracelet-02.png']},
  {slug:'red-jesper-bracelet',name:'Red Jesper Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.7',reviews:52,sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['Earth-toned stone beads for steady daily intention.','Comfortable, understated styling for everyday use.'],images:['red-jesper-bracelet-01.png','red-jesper-bracelet-02.png']},
  {slug:'rose-quartz-bracelet',name:'Rose Quartz Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.8',reviews:103,badge:'Most Rated',sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['Soft rose-toned beads for compassion-led intention-setting.','A thoughtful gift for personal rituals and connection.'],images:['rose-quartz-bracelet-01.png','rose-quartz-bracelet-02.png','rose-quartz-bracelet-03.png','rose-quartz-bracelet-04.png']},
  {slug:'sarkar-kajal',name:'Sarkar Kajal',price:'₹5,100',category:'Kajal',rating:'4.7',reviews:36,sizes:['Standard'],delivery:'Estimated delivery in 3–6 business days',benefits:['A premium ritual and beauty product in SIAOS presentation.','Compact, giftable and carefully packed.'],images:['sarkar-kajal-01.png','sarkar-kajal-02.png','sarkar-kajal-03.png']},
  {slug:'tiger-eye-bracelet',name:'Tiger Eye Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.8',reviews:97,badge:'Most Rated',sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['Golden-brown beads for focused, confident daily ritual.','A durable, versatile spiritual accessory.'],images:['tiger-eye-bracelet-01.png','tiger-eye-bracelet-02.png']},
  {slug:'yellow-citrine-bracelet',name:'Yellow Citrine Bracelet',price:'₹1,100',category:'Bracelet',rating:'4.7',reviews:67,sizes:['S · 6.5 in','M · 7 in','L · 7.5 in'],delivery:'Estimated delivery in 4–7 business days',benefits:['Bright yellow stones selected for positive daily focus.','A golden accent for mindful routines and gifting.'],images:['yellow-citrine-bracelet-01.png','yellow-citrine-bracelet-02.png']}
];
