const detailRoot=document.querySelector('#productDetail');
const slug=new URLSearchParams(location.search).get('product');
const product=window.SIAOS_PRODUCTS.find(item=>item.slug===slug)||window.SIAOS_PRODUCTS[0];
document.title=`${product.name} | SIAOS`;
const imagePath=image=>`assets/products/${product.slug}/${image}`;
const isBracelet=product.category==='Bracelet';
const subject=product.name.replace(/ Bracelet$/i,'');
const material=isBracelet?`${subject} stone beads`:product.category==='Ittar'?'Traditional fragrance blend':product.category==='Kajal'?'Ritual kajal preparation':'Sacred presentation piece';
const steps=isBracelet?[['01','Cleanse','Wipe gently with a clean, dry cloth.'],['02','Pause','Take a few calm breaths before wearing.'],['03','Intend','Choose one clear personal intention.'],['04','Wear','Wear comfortably without stretching the cord.'],['05','Care','Store separately in a dry place.']]:[['01','Prepare','Begin with clean, dry hands.'],['02','Pause','Take a quiet moment before use.'],['03','Intend','Choose one clear personal intention.'],['04','Use','Use a small amount with care.'],['05','Store','Keep closed and away from direct heat.']];
const highlights=[['Intentional practice',product.benefits[0]],['Thoughtful presentation','Carefully packed in SIAOS presentation, suitable for personal use or gifting.'],['Everyday ritual',product.benefits[1]],['Easy to care for',isBracelet?'A practical stretch design with simple care for regular wear.':'Compact presentation with simple storage and care.']];
const rows=[[5,.78],[4,.16],[3,.04],[2,.01],[1,.01]].map(([stars,share])=>[stars,Math.round(product.reviews*share)]);
detailRoot.innerHTML=`
<div class="product-breadcrumb"><a href="products.html">Store</a><span> / </span><span>${product.category}</span><span> / </span><b>${product.name}</b></div>
<section class="product-detail-layout product-commerce-hero">
 <div class="product-detail-gallery"><div class="product-image-frame"><img id="detailMainImage" src="${imagePath(product.images[0])}" alt="${product.name}">${product.badge?`<span class="product-badge">${product.badge}</span>`:''}</div><div class="detail-thumbnails">${product.images.map((image,index)=>`<button type="button" class="${index===0?'active':''}" data-image="${imagePath(image)}"><img src="${imagePath(image)}" alt="${product.name} view ${index+1}"></button>`).join('')}</div></div>
 <article class="product-detail-content"><div class="product-label-row"><span>SIAOS ${product.category}</span><span>Ready to dispatch</span></div><h1>${product.name}</h1><div class="product-rating large" aria-label="Rated ${product.rating} out of 5">★★★★★ <span>${product.rating} out of 5 · ${product.reviews} customer ratings</span></div><p class="product-intro">${product.benefits[0]} ${product.benefits[1]}</p><div class="price-panel"><p class="product-detail-price">${product.price}</p><span>Taxes included where applicable</span></div><div class="delivery-panel"><strong>Complimentary standard delivery</strong><span>${product.delivery}. Tracking details are shared after dispatch.</span></div>
 <fieldset class="option-group"><legend>${isBracelet?'Select your bracelet size':'Select size'}</legend><div class="option-pills">${product.sizes.map((size,index)=>`<button type="button" class="${index===0?'selected':''}" aria-pressed="${index===0}">${size}</button>`).join('')}</div></fieldset><div class="quantity-row"><span>Quantity</span><div><button id="decreaseQty" type="button" aria-label="Decrease quantity">−</button><output id="quantity">1</output><button id="increaseQty" type="button" aria-label="Increase quantity">+</button></div></div><div class="product-actions"><button id="addToCartButton" class="btn outline" type="button">Add to cart</button><button id="productBuyButton" class="btn fill" type="button">Buy Now · ${product.price}</button></div><p id="cartStatus" class="checkout-note" aria-live="polite">Your item, selected size and quantity will be saved securely for checkout.</p><div class="product-trust-grid"><span><b>◇</b>Secure checkout</span><span><b>⌁</b>Carefully packed</span><span><b>◎</b>Delivery tracking</span><span><b>↔</b>Size support</span><span><b>✦</b>Product care</span></div></article>
</section>
<section class="product-story-section"><header><span class="kicker">Why choose ${subject}</span><h2>A meaningful part of your daily ritual</h2><p>Designed to bring intention, beauty and a considered pause into everyday life.</p></header><div class="product-benefit-mosaic">${highlights.map((item,index)=>`<article class="benefit-${index+1}"><span>0${index+1}</span><h3>${item[0]}</h3><p>${item[1]}</p></article>`).join('')}</div></section>
<section class="product-material-section"><header><span class="kicker">Details that matter</span><h2>Material, presentation and care</h2></header><div class="material-orbit"><article><b>01</b><h3>${material}</h3><p>Selected for its colour, character and suitability for an intentional personal practice.</p></article><article><b>02</b><h3>${isBracelet?'Comfortable sizing':'Thoughtful format'}</h3><p>${isBracelet?'Three size choices help you find a comfortable everyday fit.':'Created in a compact format for considered, careful use.'}</p></article><img src="${imagePath(product.images[Math.min(1,product.images.length-1)])}" alt="${product.name} detail"><article><b>03</b><h3>SIAOS presentation</h3><p>Prepared and packed with attention before it begins its journey to you.</p></article><article><b>04</b><h3>Simple care</h3><p>Store in a dry place, handle gently and follow the included care guidance.</p></article></div></section>
<section class="product-ritual-section"><header><span class="kicker">How to use your ${product.category.toLowerCase()}</span><h2>Begin with a clear intention</h2><p>A simple five-step practice—quiet, personal and easy to follow.</p></header><div class="ritual-steps">${steps.map(step=>`<article><span>${step[0]}</span><h3>${step[1]}</h3><p>${step[2]}</p></article>`).join('')}</div><div class="intention-panel"><span>YOUR PERSONAL INTENTION</span><strong>“I welcome clarity, steadiness and mindful choices into my day.”</strong><small>You may replace this with words that feel personal to you.</small></div></section>
<section class="why-siaos-section"><header><span class="kicker">The SIAOS standard</span><h2>Why shop with SIAOS?</h2></header><div class="why-siaos-grid"><article><strong>Clear</strong><span>product information</span></article><article><strong>Careful</strong><span>presentation and packing</span></article><article><strong>Tracked</strong><span>dispatch updates</span></article><article><strong>Human</strong><span>size and order support</span></article></div><div class="brand-comparison"><div><span>Ordinary purchase</span><b>One item</b><p>Basic presentation with little guidance after purchase.</p></div><div><span>The SIAOS experience</span><b>Product + practice</b><p>Considered presentation, care guidance and a more meaningful ritual.</p></div></div></section>
<section class="product-reviews-section"><header><span class="kicker">Customer feedback</span><h2>What customers appreciate</h2></header><div class="reviews-overview"><div class="rating-total"><strong>${product.rating}</strong><span>★★★★★</span><p>Based on ${product.reviews} customer ratings</p></div><div class="rating-bars">${rows.map(row=>`<div><span>${row[0]} star</span><i><b style="width:${Math.round(row[1]/product.reviews*100)}%"></b></i><em>${row[1]}</em></div>`).join('')}</div></div><div class="review-card-grid"><article><span>★★★★★</span><h3>Beautifully presented</h3><p>“Thoughtfully packed and special from the moment it arrived.”</p><small>Customer feedback</small></article><article><span>★★★★★</span><h3>Lovely finish</h3><p>“The colour and finish are beautiful, and the size guidance was helpful.”</p><small>Customer feedback</small></article><article><span>★★★★☆</span><h3>Clear delivery updates</h3><p>“The product arrived safely and the tracking updates were easy to follow.”</p><small>Customer feedback</small></article></div></section>
<aside class="product-disclaimer">Spiritual products are intended to support personal reflection and traditional practice. Results are personal and are not guaranteed. Product information is not medical, legal or financial advice.</aside>
<div class="sticky-product-bar" aria-hidden="true"><img src="${imagePath(product.images[0])}" alt=""><div><strong>${product.name}</strong><span>${product.price}</span></div><button class="btn fill" data-sticky-buy>Buy Now</button></div>`;
document.querySelectorAll('.detail-thumbnails button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#detailMainImage').src=button.dataset.image;document.querySelectorAll('.detail-thumbnails button').forEach(item=>item.classList.remove('active'));button.classList.add('active')}));
document.querySelectorAll('.option-pills button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.option-pills button').forEach(item=>{item.classList.remove('selected');item.setAttribute('aria-pressed','false')});button.classList.add('selected');button.setAttribute('aria-pressed','true')}));
let quantity=1;const quantityOutput=document.querySelector('#quantity');document.querySelector('#decreaseQty').addEventListener('click',()=>{quantity=Math.max(1,quantity-1);quantityOutput.textContent=quantity});document.querySelector('#increaseQty').addEventListener('click',()=>{quantity+=1;quantityOutput.textContent=quantity});
const selection=()=>({slug:product.slug,name:product.name,price:product.price,size:document.querySelector('.option-pills .selected').textContent,quantity,image:imagePath(product.images[0])});
document.querySelector('#addToCartButton').addEventListener('click',()=>{const cart=JSON.parse(localStorage.getItem('siaosCart')||'[]');cart.push(selection());localStorage.setItem('siaosCart',JSON.stringify(cart));document.querySelector('#cartStatus').textContent=`Added to cart. Your cart now has ${cart.length} item${cart.length===1?'':'s'}.`});
const buyNow=()=>{localStorage.setItem('siaosPendingProduct',JSON.stringify(selection()));location.href='payment.html?product='+encodeURIComponent(product.slug)};document.querySelector('#productBuyButton').addEventListener('click',buyNow);document.querySelector('[data-sticky-buy]').addEventListener('click',buyNow);
const sticky=document.querySelector('.sticky-product-bar');window.addEventListener('scroll',()=>sticky.classList.toggle('visible',window.scrollY>650),{passive:true});
