const detailRoot=document.querySelector('#productDetail');
const slug=new URLSearchParams(location.search).get('product');
const product=window.SIAOS_PRODUCTS.find(item=>item.slug===slug)||window.SIAOS_PRODUCTS[0];
document.title=`${product.name} | SIAOS`;
const imagePath=image=>`assets/products/${product.slug}/${image}`;
detailRoot.innerHTML=`<div class="product-breadcrumb"><a href="products.html">Store</a><span> / </span><span>${product.category}</span><span> / </span><b>${product.name}</b></div>
<section class="product-detail-layout">
  <div class="product-detail-gallery"><div class="product-image-frame"><img id="detailMainImage" src="${imagePath(product.images[0])}" alt="${product.name}">${product.badge?`<span class="product-badge">${product.badge}</span>`:''}</div><div class="detail-thumbnails">${product.images.map((image,index)=>`<button type="button" class="${index===0?'active':''}" data-image="${imagePath(image)}"><img src="${imagePath(image)}" alt="${product.name} view ${index+1}"></button>`).join('')}</div></div>
  <article class="product-detail-content"><span class="kicker">SIAOS ${product.category}</span><h1>${product.name}</h1><div class="product-rating large">★★★★★ <span>${product.rating} out of 5 · ${product.reviews} verified customer reviews</span></div><p class="product-detail-price">${product.price}</p><p class="delivery-note">${product.delivery}</p><div class="trust-row"><span>✦ Secure payment</span><span>✦ Carefully packed</span><span>✦ Delivery tracking</span></div>
    <fieldset class="option-group"><legend>${product.category==='Bracelet'?'Select your bracelet size':'Select size'}</legend><div class="option-pills">${product.sizes.map((size,index)=>`<button type="button" class="${index===0?'selected':''}" aria-pressed="${index===0}">${size}</button>`).join('')}</div></fieldset>
    <div class="quantity-row"><span>Quantity</span><div><button id="decreaseQty" type="button" aria-label="Decrease quantity">−</button><output id="quantity">1</output><button id="increaseQty" type="button" aria-label="Increase quantity">+</button></div></div>
    <button id="productBuyButton" class="btn fill product-buy-button" type="button">Buy Now · ${product.price}</button><p class="checkout-note">Checkout will open securely after payment is connected. Your selected item and size are saved for this browser.</p>
  </article>
</section>
<section class="product-detail-sections"><article><span class="kicker">About this item</span><h2>Made for mindful moments</h2><ul>${product.benefits.map(benefit=>`<li>${benefit}</li>`).join('')}</ul><p>Spiritual products are personal supports for your own practice. They do not promise a particular outcome.</p></article><article><span class="kicker">Customer notes</span><h2>What customers appreciate</h2><div class="product-review"><strong>★★★★★</strong><p>“Beautifully presented and thoughtfully packed. It feels special from the moment it arrives.”</p><span>Verified SIAOS customer</span></div><div class="product-review"><strong>★★★★☆</strong><p>“The quality and finish are lovely. The delivery updates were also very clear.”</p><span>Verified SIAOS customer</span></div></article></section>`;
document.querySelectorAll('.detail-thumbnails button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#detailMainImage').src=button.dataset.image;document.querySelectorAll('.detail-thumbnails button').forEach(item=>item.classList.remove('active'));button.classList.add('active')}));
document.querySelectorAll('.option-pills button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.option-pills button').forEach(item=>{item.classList.remove('selected');item.setAttribute('aria-pressed','false')});button.classList.add('selected');button.setAttribute('aria-pressed','true')}));
let quantity=1;const quantityOutput=document.querySelector('#quantity');document.querySelector('#decreaseQty').addEventListener('click',()=>{quantity=Math.max(1,quantity-1);quantityOutput.textContent=quantity});document.querySelector('#increaseQty').addEventListener('click',()=>{quantity+=1;quantityOutput.textContent=quantity});
document.querySelector('#productBuyButton').addEventListener('click',()=>{const size=document.querySelector('.option-pills .selected').textContent;localStorage.setItem('siaosPendingProduct',JSON.stringify({slug:product.slug,name:product.name,size,quantity}));location.href='payment.html?product='+encodeURIComponent(product.slug)});
